### ISSUE TITLE
Argus Root Authorizer dump confusing role_list

### ISSUE THREAD

**Issue by hxntxng** [CoboGlobal/pycobosafe#6]
The same role is dumped twice since it is added twice into the [role_list](https://github.com/CoboGlobal/pycobosafe/blob/master/pycobosafe/authorizer.py#L84). The roles with permissions should be added to the role_list, however, I believe that roles without permissions (FlatRoleManager roles) should not. They aren't characterized under "Root Authorizer."

I propose dumping the FlatRoleManager roles someplace else, possibly the FlatRoleManager module, such that only their addresses are printed out.

**Comment by CoboMoon** [comment]
An old version `Root Authorizer` may not implement `getAllRoles` and that's why we collect roles from `FlatRoleManager` as a fallback. 
It's a bug that we add them twice. I prefer patch it like this. 
```diff
    @property
    def roles(self):
        role_list = []
        try:
            roles = self.contract.getAllRoles()
            role_list += [s32(i) for i in roles]
        except Exception:
            pass

        try:
            caller = self.caller
            if CoboSafeAccount.match(caller) or CoboSmartAccount.match(caller):
                role_mngr = CoboSafeAccount(caller).role_manager
                role_list += FlatRoleManager(role_mngr).get_all_roles()
        except Exception:
            pass

-        return role_list
+        return set(role_list)
```
